[nfs]
ansible_host=172.31.24.110 ansible_ssh_user=ec2-user

[webservers]
ansible_host=172.31.25.14 ansible_ssh_user=ec2-user
ansible_host=172.31.21.215 ansible_ssh_user=ec2-user

[db]
ansible_host=172.31.18.86 ansible_ssh_user=ec2-user 

[lb]
ansible_host=172.31.22.74 ansible_ssh_user=ubuntu


